### ISSUE TITLE
The simulator is stuck 

### ISSUE THREAD

**Issue by MohammedHossam91** [uwuser/MCsim#2]
I had an issue with MCsim while running the FRFCFS controller system and 1M_random_out trace file. MCsim stuck from the beginning of the simulation. After some debugging, I found out that it sticks in line 115 in the "Requestor.cpp" file, since the if condition in that line is always false, so the simulator keeps looping without sending any requests to the memory controller.

After further debugging, I found the root cause of this issue. In class RequestQueue, there is an uninitialized variable called writeMode. Since this variable is uninitialized, it takes a false value in most of the cases and the simulator behaves correctly, however; it can take a true value in some rare cases and cause the simulator to stick which is what happened in my case. Therefore, I suggest initializing this variable in the class constructor to ensure safe execution.

Thank you,

**Comment by rezamirosanlou** [comment]
Thanks for noticing. I was not able to reproduce the issue but I have fixed the initialization as you correctly mentioned.
